services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\EventListener\User\UserRegisterEventListener:
        class: App\EventListener\User\UserRegisterEventListener
        tags:
            - { name: 'kernel.event_listener', event: App\Event\User\UserRegisterAfterEvent, method: onUserRegister }

    App\EventListener\AuthCode\AuthCodeCreateListener:
        class: App\EventListener\AuthCode\AuthCodeCreateListener
        tags:
            - { name: 'kernel.event_listener', event: App\Event\AuthCode\AuthCodeCreateAfterEvent, method: onAuthCodeCreate }