security:
    encoders:
        App\Entity\User:
            id: App\Service\Security\NoPasswordEncoder
    providers:
        users:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        doc:
            security: false
            pattern: ^/v\d+/doc
        v1_login:
            pattern:  ^/v1/auth/login
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - App\Service\Security\UsernameOrEmailAuthenticator
        v1_login_confirm:
            pattern:  ^/v1/auth/confirm
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - App\Service\Security\EmailCodeAuthenticator
#            json_login:
#                check_path: /v1/auth/login
#                password_path: username
#                success_handler: lexik_jwt_authentication.handler.authentication_success
#                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        v1_auth:
            pattern:  ^/v1/auth
            stateless: true
            anonymous: true
        v1_api:
            pattern: ^/v1
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/v1/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1, roles: IS_AUTHENTICATED_FULLY }