version: '3.7'

volumes:
    db_data: {}
    db_test_data: {}

services:
    php:
        build:
            context: docker/php
            args:
                PHP_VERSION: 7.4
                USER_GID: 1000
                USER_UID: 1000
                WAIT_FOR_HOST: postgres
                WAIT_FOR_PORT: 5432
        environment:
            DEV_MODE: 0
        restart: always
        volumes:
            - .:/srv:rw
        networks:
            auth:
            f1monkey:
                aliases:
                    - f1monkey-elastic
    postgres:
        image: postgres:12.3-alpine
        environment:
            POSTGRES_DB: auth_service
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - "db_data:/var/lib/postgresql/data"
        networks:
            auth:

    mail:
        image: mailhog/mailhog:latest

    postgres_test:
        image: postgres:12.3-alpine
        environment:
            POSTGRES_DB: auth_service_test
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - "db_test_data:/var/lib/postgresql/data"
        networks:
            auth:

networks:
    f1monkey:
        external: true
    auth: