imports:
    - { resource: services/doctrine.yaml }
    - { resource: services/events.yaml }
    - { resource: services/log.yaml }

parameters:
    app.auth_code.max_per_user: 5
    app.auth_code.lifetime: 900

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,EventListener,Entity,Exception,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\AuthCode\AuthCodeManagerInterface:
        class: App\Service\AuthCode\AuthCodeManager
        arguments:
            $maxPerUser: '%app.auth_code.max_per_user%'
            $codeLifetime: '%app.auth_code.lifetime%'

    Gesdinet\JWTRefreshTokenBundle\Service\RefreshToken:
        alias: gesdinet.jwtrefreshtoken