parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    test.app.user_manager:
        alias: App\Service\User\UserManagerInterface

    test.app.user_register_service:
        alias: App\Service\User\UserRegisterServiceInterface

    test.app.auth_code_manager:
        alias: App\Service\AuthCode\AuthCodeManagerInterface

    Symfony\Component\Mailer\MailerInterface:
        class: App\Tests\_support\Mock\MailerMock