parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    test.app.user_manager:
        alias: App\Service\User\UserManagerInterface

    test.app.auth_code_manager:
        alias: App\Service\AuthCode\AuthCodeManagerInterface